server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec?useSSl=ture&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher